### ISSUE TITLE
How

### ISSUE THREAD

**Issue by xiaobaoxia** [aidarikako/JMDA#1]

**Comment by xiaobaoxia** [comment]
Hi there,

I only find the align_two_data function in feeders\tools.py, could I ask how to align one subject sample and two subjects sample in code?

Thanks for this excellent work.

**Comment by aidarikako** [comment]
> Hi there,
> 
> I only find the align_two_data function in feeders\tools.py, could I ask how to align one subject sample and two subjects sample in code?
> 
> Thanks for this excellent work.

In fact, within the "ctrgcn" folder, in the "feeders\tools.py" file, lines 53–54 contains the "P" (paste operation) mentioned in the Feature Alignment section of our paper.  Subsequently, lines 72–78 implement the "R" (resize operation).  Since the original CTR-GCN paper already applies the "R" operation during preprocessing, we only need to add the "P" operation. The "align_two_data" function you mentioned is unrelated to this paper. It is a function used in other experiments and was mistakenly left in the uploaded code.

**Comment by aidarikako** [comment]
> Hi there,
> 
> I only find the align_two_data function in feeders\tools.py, could I ask how to align one subject sample and two subjects sample in code?
> 
> Thanks for this excellent work.

```   
if np.sum(data_numpy[:, :, :, 1].sum(0).sum(-1) != 0) == 0:
        data_numpy[:, :, :, 1] = data_numpy[:, :, :, 0] 
```

**Comment by xiaobaoxia** [comment]
Thanks for your reply, it helps me a lot.
